sudo: false
language: c

matrix:
  include:
    # Linux with GNU C Compiler
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - gcc
            - cmake
            - cmake-data
            - libpcsclite-dev
  
    # Linux with LLVM C Compiler
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - clang
            - cmake
            - cmake-data
            - libpcsclite-dev

    # MacOS X 10.10 (Yosemite)
    - os: osx
      osx_image: xcode6.4
      compiler: clang

    # MacOS X 10.11 (El Captain)
    - os: osx
      osx_image: xcode7.3
      compiler: clang

    # macOS 10.11 (Sierra)
    - os: osx 
      osx_image: xcode8
      compiler: clang

script:
  - install -d build
  - cd build
  - cmake ..
  - make VERBOSE=1
  - ./b25 2>&1 | grep "ARIB STD-B25"
